import { z } from "zod";

export const AudioStream = z.object({
  index: z.number(),
  codec_name: z.string(),
  codec_long_name: z.string(),
  profile: z.string(),
  codec_type: z.string(),
  codec_tag_string: z.string(),
  codec_tag: z.string(),
  sample_fmt: z.string(),
  sample_rate: z.string(),
  channels: z.number(),
  channel_layout: z.string(),
  bits_per_sample: z.number(),
  initial_padding: z.number(),
  id: z.string(),
  r_frame_rate: z.string(),
  avg_frame_rate: z.string(),
  time_base: z.string(),
  start_pts: z.number(),
  start_time: z.string(),
  duration_ts: z.number(),
  duration: z.string(),
  bit_rate: z.string(),
  nb_frames: z.string(),
  extradata_size: z.number(),
  disposition: z.object({
    default: z.number(),
    dub: z.number(),
    original: z.number(),
    comment: z.number(),
    lyrics: z.number(),
    karaoke: z.number(),
    forced: z.number(),
    hearing_impaired: z.number(),
    visual_impaired: z.number(),
    clean_effects: z.number(),
    attached_pic: z.number(),
    timed_thumbnails: z.number(),
    non_diegetic: z.number(),
    captions: z.number(),
    descriptions: z.number(),
    metadata: z.number(),
    dependent: z.number(),
    still_image: z.number(),
  }),
  tags: z.object({
    language: z.string(),
    handler_name: z.string(),
    vendor_id: z.string(),
  }),
});

export const VideoStream = z.object({
  index: z.number(),
  codec_name: z.string(),
  codec_long_name: z.string(),
  profile: z.string(),
  codec_type: z.string(),
  codec_tag_string: z.string(),
  codec_tag: z.string(),
  width: z.number(),
  height: z.number(),
  coded_width: z.number(),
  coded_height: z.number(),
  closed_captions: z.number(),
  film_grain: z.number(),
  has_b_frames: z.number(),
  sample_aspect_ratio: z.string(),
  display_aspect_ratio: z.string(),
  pix_fmt: z.string(),
  level: z.number(),
  color_range: z.string(),
  color_space: z.string(),
  color_transfer: z.string(),
  color_primaries: z.string(),
  chroma_location: z.string(),
  field_order: z.string(),
  refs: z.number(),
  is_avc: z.string(),
  nal_length_size: z.string(),
  id: z.string(),
  r_frame_rate: z.string(),
  avg_frame_rate: z.string(),
  time_base: z.string(),
  start_pts: z.number(),
  start_time: z.string(),
  duration_ts: z.number(),
  duration: z.string(),
  bit_rate: z.string(),
  bits_per_raw_sample: z.string(),
  nb_frames: z.string(),
  extradata_size: z.number(),
  disposition: z.object({
    default: z.number(),
    dub: z.number(),
    original: z.number(),
    comment: z.number(),
    lyrics: z.number(),
    karaoke: z.number(),
    forced: z.number(),
    hearing_impaired: z.number(),
    visual_impaired: z.number(),
    clean_effects: z.number(),
    attached_pic: z.number(),
    timed_thumbnails: z.number(),
    non_diegetic: z.number(),
    captions: z.number(),
    descriptions: z.number(),
    metadata: z.number(),
    dependent: z.number(),
    still_image: z.number(),
  }),
  tags: z.object({
    language: z.string(),
    handler_name: z.string(),
    vendor_id: z.string(),
  }),
});

export const FfprobeFormat = z.object({
  filename: z.string(),
  nb_streams: z.number(),
  nb_programs: z.number(),
  nb_stream_groups: z.number(),
  format_name: z.string(),
  format_long_name: z.string(),
  start_time: z.string(),
  duration: z.string(),
  size: z.string(),
  bit_rate: z.string(),
  probe_score: z.number(),
  tags: z.object({
    major_brand: z.string(),
    minor_version: z.string(),
    compatible_brands: z.string(),
    encoder: z.string(),
  }),
});

export const FfprobeSchema = z.object({
  streams: z.array(z.union([VideoStream, AudioStream])),
  format: FfprobeFormat,
});
