name: CI Build & Upload Extensions

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  upload-extensions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.10
      - run: pnpm i
      - name: Docker Build and Uplad Extensions
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        working-directory: ci
        run: |
          pnpm --filter ci build-upload
